"""Added refresh_token and access_expr fields to User

Revision ID: b7c48589ca2a
Revises: ee2b22119072
Create Date: 2019-11-25 12:03:33.041092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c48589ca2a'
down_revision = 'ee2b22119072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_expr', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_expr')
    # ### end Alembic commands ###
